[profile.default]
src = 'src'
out = 'out'

optimizer = true
optimizer_runs = 10_000
fs_permissions = [{ access = "read-write", path = "./"}]

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
optimism = "${OP_RPC_URL}"
arbitrum = "${ARBI_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }
optimism = { key = "${OP_ETHERSCAN_API_KEY}" }
arbitrum = { key = "${ARBI_ETHERSCAN_API_KEY}" }

[fmt]
line_length = 120
tab_width = 2
bracket_spacing = false
int_types = 'short'
func_attrs_with_params_multiline = false
quote_style = 'double'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config